# This is a basic workflow to help you get started with Actions

name: DotNet Framework CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      # Restore NuGet Packages
      - name: Restore NuGet Packages
        run: nuget restore ./Rest/Rest.sln
        
      # Build Solution
      - name: Build Solution
        run: msbuild ./Rest/Rest.sln /p:Configuration=Release
        
      # Install vstest
      - name: Install VS Test
        run: nuget install Microsoft.TestPlatform -ExcludeVersion
        
      # Run Unit Tests  
      - name: Run Unit Tests
        run: ./Microsoft.TestPlatform/tools/net451/Common7/IDE/Extensions/TestPlatform/vstest.console.exe ./Rest/RestTests/bin/Release/RestTests.dll
