name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore .\Rest\Rest.sln
      
    - name: Build
      run: dotnet build .\Rest\Rest.sln
      
    - name: Test
      run: dotnet test .\Rest\Rest.sln --settings .\Rest\actions.runsettings 
    

